/**
 * @brief Implementation of FSM (finite state machine) for controlling a LED.
 *  
 *        The following states are implemented:
 *            - STATE_OFF  : The LED is disabled.
 *            - STATE_BLINK: The LED is blinking every 100 ms.
 *            - STATE_ON   : The LED is enabled.
 *
 *        The state is updated to next/previous via two buttons. A third
 *        button is used to generate system reset. 
 *
 * @note See 'system.h' for PIN, state, and event definitions.
 */
#include "system.h"

/**
 * @brief Handle button event whenever a button is pressed. 
 */
ISR (PCINT0_vect)
{
    system_handle_event(EVENT_BUTTON);
}

/**
 * @brief Handle event whenever an interrupt is generated by Timer 0.
 */
ISR (TIMER0_OVF_vect)
{
    system_handle_event(EVENT_TIMER0);
}

/**
 * @brief Handle event whenever an interrupt is generated by Timer 1.
 */
ISR (TIMER1_COMPA_vect)
{
    system_handle_event(EVENT_TIMER1);
}

/**
 * @brief Set up the system and run the state machine continuously.
 *
 * @return Success code 0 when the program terminates (should never occur).
 */
int main(void)
{
    system_setup();
    while (1) {}
}
